export { default as Footer} from './Footer';
export { default as Form } from './Form';
export {default as Navbar} from './Navbar';
export { default as Profile } from './Profile';
export {default as Service} from './Service';
export {default as Table } from './Table';
export { default as Nav1} from './SVG/Nav1';
export { default as Nav2} from './SVG/Nav2';
export { default as Nav3} from './SVG/Nav3';
export { default as Fot1} from './SVG/Fot1';
export { default as Fot2} from './SVG/Fot2';
export { default as Str1} from './SVG/Str1';
export {default as Logo} from './SVG/logo.png';
export {default as ImgHero} from './SVG/deednft.png';
export {default as ImgStep} from './SVG/landf.png';
export {default as Hero} from './Hero';
export {default as Statistic} from './Statistic';
export {default as Step} from './Step';
export {default as GetStarted} from './GetStarted';